### ISSUE TITLE
d3net example graphs not rendering

### ISSUE THREAD

**Issue by brooksandrew** [mbojan/d3net#22]
I tried latest version of you package on Windows and Mac and i'm not seeing the first couple graphs render from the examples.  The dynamic graph does work with the latest commit for me.  I was able to get the examples and some of my graphs to render with a prior commit (99df1d5).  Perhaps a merge issue with recent commits?

**Comment by mbojan** [comment]
Thanks for reporting. I have some questions:

1. So for you examples and your graphs do not render with version https://github.com/mbojan/d3net/commit/99df1d5a4bca89f98bc353ef32d540e9477c7bda or later?

2. What browser are you using?

**Comment by brooksandrew** [comment]
1. I just tried 99df1d5.  The examples and the graphs I'm working with rendered well.
2. IE on Windows and Chrome on Mac

**Comment by mbojan** [comment]
Hmm that's curious... 

Are you sure you have the latest version 327c43a014e7bb87b23a77eea271b19df8e86685 ? @pawluczuk did some fixing couple of days ago.

Can you see any javascript errors in the browser console (in Chrome menu "more tools">>"developer tools" https://developer.chrome.com/devtools/docs/console )?

**Comment by pawluczuk** [comment]
@brooksandrew  Can you tell us which Shiny version you are using? If you can render graphs for dynamic graphs, probably you're using older version of Shiny. Application that is rendering graphs for igraph and network is using new Shiny UI components, maybe that is the issue.

**Comment by brooksandrew** [comment]
Ah I think that's the issue.  I just tried on a different computer with shiny 0.12.2 and the examples all work.  easy fix.  thanks!
