### ISSUE TITLE
Embedding in RMarkdown documents

### ISSUE THREAD

**Issue by mbojan** [mbojan/d3net#23]
See http://rmarkdown.rstudio.com/authoring_embedded_shiny.html
Calling `d3net` in code chunk does not seem to work.

**Comment by pawluczuk** [comment]
Do you mean including d3net in a script or in a document (like in the link included)?

**Comment by pawluczuk** [comment]
It seems that Rmd file doesn't have an access to R files and libraries. If you add all the libraries in the R chunk and set Output format to Shiny HTML embedding works OK (at least on Mac).

You can also embed plots, for example:
```
```{r, echo=FALSE}
library(d3net)
library(igraphdata)
data(karate)
d3net(karate)
.``` (dot added so that it doesn't disappear)
```

**Comment by mbojan** [comment]
Works indeed. I forgot to set `runtime: shiny`... :P
